version: "3"

services:
  app-i1:
    image: debian
    ports:
      - 3000:3000
    environment:
      - INSTANCE=7
      - PORT=3000
  app-i2:
    image: debian
    ports:
      - 3001:3001
    environment:
      - INSTANCE=8
      - PORT=3001
  app-i3:
    image: debian
    ports:
      - 3002:3002
    environment:
      - INSTANCE=9
      - PORT=3002
  balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app-i1
      - app-i2
      - app-i3